//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrashCollector.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TrashCollector.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Name&quot;,&quot;Abbreviation&quot;
        ///&quot;Alabama&quot;,&quot;AL&quot;
        ///&quot;Alaska&quot;,&quot;AK&quot;
        ///&quot;Arizona&quot;,&quot;AZ&quot;
        ///&quot;Arkansas&quot;,&quot;AR&quot;
        ///&quot;California&quot;,&quot;CA&quot;
        ///&quot;Colorado&quot;,&quot;CO&quot;
        ///&quot;Connecticut&quot;,&quot;CT&quot;
        ///&quot;Delaware&quot;,&quot;DE&quot;
        ///&quot;District of Columbia&quot;,&quot;DC&quot;
        ///&quot;Florida&quot;,&quot;FL&quot;
        ///&quot;Georgia&quot;,&quot;GA&quot;
        ///&quot;Hawaii&quot;,&quot;HI&quot;
        ///&quot;Idaho&quot;,&quot;ID&quot;
        ///&quot;Illinois&quot;,&quot;IL&quot;
        ///&quot;Indiana&quot;,&quot;IN&quot;
        ///&quot;Iowa&quot;,&quot;IA&quot;
        ///&quot;Kansas&quot;,&quot;KS&quot;
        ///&quot;Kentucky&quot;,&quot;KY&quot;
        ///&quot;Louisiana&quot;,&quot;LA&quot;
        ///&quot;Maine&quot;,&quot;ME&quot;
        ///&quot;Montana&quot;,&quot;MT&quot;
        ///&quot;Nebraska&quot;,&quot;NE&quot;
        ///&quot;Nevada&quot;,&quot;NV&quot;
        ///&quot;New Hampshire&quot;,&quot;NH&quot;
        ///&quot;New Jersey&quot;,&quot;NJ&quot;
        ///&quot;New Mexico&quot;,&quot;NM&quot;
        ///&quot;New York&quot;,&quot;NY&quot;
        ///&quo....
        /// </summary>
        internal static string states {
            get {
                return ResourceManager.GetString("states", resourceCulture);
            }
        }
    }
}
